version: '3.3'

services:

  vantaa-pwa:
    image: vantaa-exercise-reservations:latest
    ports:
      - 5000:5000
    command: bash -c 'npm install && npm start && npm run fetch-courses'
    depends_on:
      - postgres-dev-db
    environment:
      PORT: 5000
      USERNAME: postgres
      PASSWORD: password
      DATABASE: vantaa_pwa
      HOST: postgres-dev-db
      GRYNOS_COURSES_UPDATE_INTERVAL: 3600000
      GRYNOS_COURSE_API_URL: https://colosseum.grynos.com/ilmoapix/v1/course/search?com=3,6&cgt=176
      POPULATE_SEED_DATA: 1
      PAYMENT_RETURN_URL: https://vantaa-silverfox.herokuapp.com/api/payments/paymentReturn
      PAYMENT_NOTIFY_URL: https://vantaa-silverfox.herokuapp.com/api/payments/paymentNotify
      SECRET_KEY: secret_key
      API_KEY: api_key


  postgres-dev-db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vantaa_pwa

  admin:
    image: adminer
    ports:
      - 8080:8080